# For more details on app.yaml, see: https://aka.ms/coral/appyaml

template: external-service
deployments:
  development:
    target: development
    clusters: 1
    values:
      fqdn: forex-dev.contoso.com
      image: ghcr.io/rajkalemsft/coral-sample-dotnet:main
      healthEndpoint: /healthz
      port: 5000
      cpu: 1
      memory: 256M
      replicas: 1
